### ISSUE TITLE
build-disk panics if no config provided

### ISSUE THREAD

**Issue by Itxaka** [rancher/elemental-cli#248]
```
$ sudo bin/elemental build-disk --debug                            
DEBU[2022-06-09T14:22:43+02:00] Starting elemental version v0.0.15 on commit 73aa161d1a5d82a2117e150030d60f1a16830824 
DEBU[2022-06-09T14:22:43+02:00] Full config loaded: &v1.BuildConfig{
  Date: false,
  Name: "elemental",
  OutDir: "",
  Config: v1.Config{
    Logger: &v1.logrusWrapper{ // p0
      Logger: &logrus.Logger{
        Out: &os.File{},
        Hooks: logrus.LevelHooks{},
        Formatter: &logrus.TextFormatter{
          ForceColors: true,
          DisableColors: false,
          ForceQuote: false,
          DisableQuote: false,
          EnvironmentOverrideColors: false,
          DisableTimestamp: false,
          FullTimestamp: true,
          TimestampFormat: "",
          DisableSorting: false,
          SortingFunc: ,
          DisableLevelTruncation: false,
          PadLevelText: false,
          QuoteEmptyFields: false,
          FieldMap: logrus.FieldMap(nil),
          CallerPrettyfier: ,
        },
        ReportCaller: false,
        Level: 5,
        ExitFunc: os.Exit,
      },
    },
    Fs: &vfs.osfs{}, // p1
    Mounter: &mount.FakeMounter{
      MountPoints: nil,
      MountCheckErrors: map[string]error(nil),
      UnmountFunc: ,
    },
    Runner: &v1.RealRunner{ // p2
      Logger: p0,
    },
    Syscall: &v1.RealSyscall{},
    CloudInitRunner: &cloudinit.YipCloudInitRunner{},
    Luet: &luet.Luet{
      VerifyImageUnpack: false,
      TmpDir: "",
    },
    Client: &http.Client{},
    Cosign: false,
    Verify: false,
    CosignPubKey: "",
    LocalImage: false,
    Repos: []v1.Repository{
      v1.Repository{
        Name: "cos",
        Priority: 90,
        URI: "quay.io/costoolkit/releases-green",
        Type: "docker",
        Arch: "",
        ReferenceID: "",
      },
    },
    Arch: "x86_64",
    SquashFsCompressionConfig: []string{
      "-comp",
      "xz",
      "-Xbcj",
      "x86",
    },
  },
} 
WARN[2022-06-09T14:22:43+02:00] error unmarshalling RawDisk: 1 error(s) decoding:

* '[debug]' expected a map, got 'bool' 
DEBU[2022-06-09T14:22:43+02:00] Loaded RawDisk: &v1.RawDisk{}                
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11a7e4e]

goroutine 1 [running]:
github.com/rancher/elemental-cli/cmd.NewBuildDisk.func2(0xc00041bb80, {0xc000287550?, 0x1?, 0x1?})
	/home/itxaka/projects/elemental-cli/cmd/build-disk.go:79 +0x1ce
github.com/spf13/cobra.(*Command).execute(0xc00041bb80, {0xc000287540, 0x1, 0x1})
	/home/itxaka/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00041b900)
	/home/itxaka/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/itxaka/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/rancher/elemental-cli/cmd.Execute()
	/home/itxaka/projects/elemental-cli/cmd/root.go:48 +0x25
main.main()
	/home/itxaka/projects/elemental-cli/main.go:21 +0x17

```

**Comment by Itxaka** [comment]
This comes becuase we are returning an empty RawDisk config for some reason...?

**Comment by Itxaka** [comment]
Looks like the unmarshal is breaking this, no idea why. Any hints @davidcassany ?

**Comment by Itxaka** [comment]
looks like its the `config.ZeroFields = true` the one that is removing the whole thing, Im guessing because we have the arches is a slice, it gets fully removed :/

**Comment by frelon** [comment]
This seems like a regression, I don't get it on my branch from 73aa161:

```
$ sudo bin/elemental build-disk                                                                                                                                   14:37:22
INFO[2022-06-09T14:37:26+02:00] Starting elemental version v0.0.15
INFO[2022-06-09T14:37:26+02:00] Building disk image type raw for arch x86_64
ERRO[2022-06-09T14:37:26+02:00] no values in the config for arch x86_64
```

**Comment by Itxaka** [comment]
@frelon is you binary rebuilt? Im on the same branch, latest main and still getting it!

`commit 73aa161d1a5d82a2117e150030d60f1a16830824 HEAD (HEAD -> main, upstream/main, origin/main)`

```
$ make build && sudo bin/elemental version --long && sudo bin/elemental build-disk --debug
go build -ldflags '-w -s -X "github.com/rancher/elemental-cli/internal/version.version=v0.0.15" -X "github.com/rancher/elemental-cli/internal/version.gitCommit=73aa161d1a5d82a2117e150030d60f1a16830824"' -o bin/elemental
version.BuildInfo{Version:"v0.0.15", GitCommit:"73aa161d1a5d82a2117e150030d60f1a16830824", GoVersion:"go1.18.2"}DEBU[2022-06-09T14:41:05+02:00] Starting elemental version v0.0.15 on commit 73aa161d1a5d82a2117e150030d60f1a16830824 
DEBU[2022-06-09T14:41:05+02:00] Full config loaded: &v1.BuildConfig{
  Date: false,
  Name: "elemental",
  OutDir: "",
  Config: v1.Config{
    Logger: &v1.logrusWrapper{ // p0
      Logger: &logrus.Logger{
        Out: &os.File{},
        Hooks: logrus.LevelHooks{},
        Formatter: &logrus.TextFormatter{
          ForceColors: true,
          DisableColors: false,
          ForceQuote: false,
          DisableQuote: false,
          EnvironmentOverrideColors: false,
          DisableTimestamp: false,
          FullTimestamp: true,
          TimestampFormat: "",
          DisableSorting: false,
          SortingFunc: ,
          DisableLevelTruncation: false,
          PadLevelText: false,
          QuoteEmptyFields: false,
          FieldMap: logrus.FieldMap(nil),
          CallerPrettyfier: ,
        },
        ReportCaller: false,
        Level: 5,
        ExitFunc: os.Exit,
      },
    },
    Fs: &vfs.osfs{}, // p1
    Mounter: &mount.FakeMounter{
      MountPoints: nil,
      MountCheckErrors: map[string]error(nil),
      UnmountFunc: ,
    },
    Runner: &v1.RealRunner{ // p2
      Logger: p0,
    },
    Syscall: &v1.RealSyscall{},
    CloudInitRunner: &cloudinit.YipCloudInitRunner{},
    Luet: &luet.Luet{
      VerifyImageUnpack: false,
      TmpDir: "",
    },
    Client: &http.Client{},
    Cosign: false,
    Verify: false,
    CosignPubKey: "",
    LocalImage: false,
    Repos: []v1.Repository{
      v1.Repository{
        Name: "cos",
        Priority: 90,
        URI: "quay.io/costoolkit/releases-green",
        Type: "docker",
        Arch: "",
        ReferenceID: "",
      },
    },
    Arch: "x86_64",
    SquashFsCompressionConfig: []string{
      "-comp",
      "xz",
      "-Xbcj",
      "x86",
    },
  },
} 
WARN[2022-06-09T14:41:05+02:00] error unmarshalling RawDisk: 1 error(s) decoding:

* '[debug]' expected a map, got 'bool' 
DEBU[2022-06-09T14:41:05+02:00] Loaded RawDisk: &v1.RawDisk{}                
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11a7e4e]

goroutine 1 [running]:
github.com/rancher/elemental-cli/cmd.NewBuildDisk.func2(0xc0003ad680, {0xc000254790?, 0x1?, 0x1?})
	/home/itxaka/projects/elemental-cli/cmd/build-disk.go:79 +0x1ce
github.com/spf13/cobra.(*Command).execute(0xc0003ad680, {0xc000254780, 0x1, 0x1})
	/home/itxaka/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003ad400)
	/home/itxaka/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/itxaka/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/rancher/elemental-cli/cmd.Execute()
	/home/itxaka/projects/elemental-cli/cmd/root.go:48 +0x25
main.main()
	/home/itxaka/projects/elemental-cli/main.go:21 +0x17

```

**Comment by frelon** [comment]
Yep it was rebuilt but I get the same error when running from main... Seems like I accidentally fixed it somehow

**Comment by Itxaka** [comment]
very easy fix, but not sure about the implications, will send a PR for it and wait for some feedback from the viper master :P
